### ISSUE TITLE
Can't be installed

### ISSUE THREAD

**Issue by ledermann** [mikel/tmail#4]
I'm trying to install the gem with:
    gem sources -a http://gems.github.com
    sudo gem install mikel-tmail

But I always get:
    ERROR:  could not find gem mikel-tmail locally or in a repository

Then I use the installation hint from the README:
    sudo gem install tmail

But this installes an old version:
    Installing ri documentation for tmail-1.2.3.1...
    Installing RDoc documentation for tmail-1.2.3.1...

What is the prefered way to use the current gem 1.2.5 in a Rails application?

**Comment by mikel** [comment]
You can install it with "gem install tmail" now, TMail is on Gemcutter
